-- CreateTable
CREATE TABLE "TabelNeracaAir" (
    "id" SERIAL NOT NULL,
    "bulan" TEXT NOT NULL DEFAULT 'Januari',
    "CH" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "t_avg" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "etp" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "ch_etp" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "apwl" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "kat" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "ats_percentage" DOUBLE PRECISION NOT NULL DEFAULT 0,

    CONSTRAINT "TabelNeracaAir_pkey" PRIMARY KEY ("id")
);
