-- CreateTable
CREATE TABLE "SensorLogs" (
    "id" SERIAL NOT NULL,
    "cloud" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "thermostat" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "eye" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "pressure" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "wind" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "noise" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "temperature" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "timestamp" TEXT,
    "createdAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SensorLogs_pkey" PRIMARY KEY ("id")
);
