-- CreateTable
CREATE TABLE "Sensors" (
    "id" SERIAL NOT NULL,
    "w1_hum" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w1_temp" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w1_noise" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w1_pm25" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w1_pm10" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w1_press" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w1_luxh" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w1_luxl" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w2_wd" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w2_ws_avg" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w2_ws_max" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w2_rain_h" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w2_rain_d" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w2_temp" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w2_hum" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "w2_press" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Sensors_pkey" PRIMARY KEY ("id")
);
